steps:
  - label: "Bundle Android"
    key: "bundle-android"
    plugins:
      - docker#v3.8.0:
          image: "oguzkocer/gb-mobile-image"
    command: |
        source /root/.bashrc
        git submodule update --init --recursive

        cp gutenberg/.nvmrc ./.nvmrc
        nvm install && nvm use
        npm ci --unsafe-perm --prefer-offline --no-audit --no-progress

        npm run prebundle:js
        npm run bundle:android

        buildkite-agent artifact upload bundle/android/App.js

  - label: "Build Android RN Bridge & Publish to S3"
    depends_on: "bundle-android"
    plugins:
      - docker#v3.8.0:
          image: "oguzkocer/android-image"
    command: |
        cd ./gutenberg/packages/react-native-bridge/android
        mkdir -p ./react-native-bridge/build/assets
        buildkite-agent artifact download bundle/android/App.js ./react-native-bridge/build/assets/index.android.bundle
        # TODO: Use the correct version
        ./publish-aztec-and-bridge.sh "test-build-kite-integration"
