steps:
  - label: "Bundle Android"
    key: "bundle-android"
    plugins:
      - docker#v3.8.0:
          image: "oguzkocer/gb-mobile-image"
          environment:
            - "CI=true"
    command: |
        source /root/.bashrc

        pushd gutenberg && nvm install && nvm use && popd
        npm ci --unsafe-perm --prefer-offline --no-audit --no-progress

        npm run prebundle:js
        npm run bundle:android

        buildkite-agent artifact upload bundle/android/App.js

  - label: "Build Android RN Bridge & Publish to S3"
    depends_on: "bundle-android"
    plugins:
      - docker#v3.8.0:
          image: "public.ecr.aws/m4u4m2y0/android-build-image:02db9ae7aea96f767be97dcc17db677d37e41480"
          environment:
            propagate-environment: true
    command: |
        buildkite-agent artifact download bundle/android/App.js .
        mkdir -p gutenberg/packages/react-native-bridge/android/react-native-bridge/build/assets
        cp ./bundle/android/App.js ./gutenberg/packages/react-native-bridge/android/react-native-bridge/build/assets/index.android.bundle

        source /scripts/prepare_to_publish_to_s3_params.sh

        pushd ./gutenberg/packages/react-native-aztec/android
        ./gradlew -PwillPublishReactNativeAztecBinary=true :prepareToPublishToS3 $(prepare_to_publish_to_s3_params) :publish
        popd

        pushd ./gutenberg/packages/react-native-bridge/android
        ./gradlew -PwillPublishReactNativeBridgeBinary=true -PreactNativeAztecVersion="$VERSION" :react-native-bridge:prepareToPublishToS3 $(prepare_to_publish_to_s3_params) :react-native-bridge:publish
