steps:
  - label: "Build Android RN Bridge & Publish to S3"
    plugins:
      - docker#v3.8.0:
          image: "wordpressmobile/gb-mobile-android-build-image"
          propagate-environment: true
    command: |
        source /root/.bashrc
        git submodule update --init --recursive

        cp gutenberg/.nvmrc ./.nvmrc
        nvm install && nvm use
        npm ci --unsafe-perm --prefer-offline --no-audit --no-progress

        npm run prebundle:js
        npm run bundle:android
        cd gutenberg/packages/react-native-bridge/android
        # TODO: Use the correct version
        ./publish-aztec-and-bridge.sh "test-build-kite-integration"

