steps:
  - label: "Bundle Android"
    key: "bundle-android"
    plugins:
      - docker#v3.8.0:
          image: "oguzkocer/gb-mobile-image"
          environment:
            - "CI=true"
    command: |
        source /root/.bashrc

        pushd gutenberg && nvm install && nvm use && popd
        npm ci --unsafe-perm --prefer-offline --no-audit --no-progress

        npm run prebundle:js
        npm run bundle:android

        buildkite-agent artifact upload bundle/android/App.js

  - label: "Build Android RN Bridge & Publish to S3"
    depends_on: "bundle-android"
    plugins:
      - docker#v3.8.0:
          image: "public.ecr.aws/m4u4m2y0/android-build-image:latest"
          environment:
            - "CI=true"
            # DO NOT MANUALLY SET THESE VALUES!
            # They are passed from the BuildKite agent to the Docker container
            - "AWS_ACCESS_KEY"
            - "AWS_SECRET_KEY"
    command: |
        buildkite-agent artifact download bundle/android/App.js .
        mkdir -p gutenberg/packages/react-native-bridge/android/react-native-bridge/build/assets
        cp ./bundle/android/App.js ./gutenberg/packages/react-native-bridge/android/react-native-bridge/build/assets/index.android.bundle
        # TODO: Use the correct version
        ./publish-react-native-aztec-and-react-native-bridge.sh "test-build-kite-integration-$(date -u +%s)"
