steps:
  - label: "Bundle Android"
    key: "bundle-android"
    plugins:
      - docker#v3.8.0:
          image: "oguzkocer/gb-mobile-image"
    command: |
        source /root/.bashrc

        cp gutenberg/.nvmrc ./.nvmrc
        nvm install && nvm use
        npm ci --unsafe-perm --prefer-offline --no-audit --no-progress

        npm run prebundle:js
        npm run bundle:android

        buildkite-agent artifact upload bundle/android/App.js

  - label: "Build Android RN Bridge & Publish to S3"
    depends_on: "bundle-android"
    plugins:
      - docker#v3.8.0:
          image: "oguzkocer/android-image"
          environment:
            # DO NOT MANUALLY SET THESE VALUES!
            # They are passed from the BuildKite agent to the Docker container
            - "AWS_ACCESS_KEY"
            - "AWS_SECRET_KEY"
    command: |
        buildkite-agent artifact download bundle/android/App.js .
        # TODO: Use the correct version
        ./gutenberg/packages/react-native-bridge/android/publish-aztec-and-bridge.sh "test-build-kite-integration-$(date -u +%s)"
        echo "Finished running at: $(date -u)"
